In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1) #axis 1 is columns

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['t','u','v'])
ser2 = Series([3,4],index=['x','y'])

In [7]:
ser1

t    0
u    1
v    2
dtype: int64

In [8]:
ser2

x    3
y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2]) #default on rows

t    0
u    1
v    2
x    3
y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2], axis=1) #creates dataframe since it contains null info

0   1
t   0 NaN
u   1 NaN
v   2 NaN
x NaN   3
y NaN   4

In [14]:
pd.concat([ser1,ser2],keys=['cat1','cat2']) #creates hierarchical index

cat1  t    0
      u    1
      v    2
cat2  x    3
      y    4
dtype: int64

In [15]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['x','y','z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['y','q','x'])

In [16]:
dframe1

x         y         z
0  0.964260 -0.787730  0.120274
1  0.557330 -1.408828  0.217862
2 -0.010404  0.829389  0.419324
3  0.358809 -0.026852  0.906940

In [17]:
dframe2

y         q         x
0  2.160294  0.477203  0.274342
1 -1.665423  1.028196 -1.242782
2 -0.572431 -0.932193  0.783536

In [18]:
pd.concat([dframe1,dframe2])

q         x         y         z
0       NaN  0.964260 -0.787730  0.120274
1       NaN  0.557330 -1.408828  0.217862
2       NaN -0.010404  0.829389  0.419324
3       NaN  0.358809 -0.026852  0.906940
0  0.477203  0.274342  2.160294       NaN
1  1.028196 -1.242782 -1.665423       NaN
2 -0.932193  0.783536 -0.572431       NaN

In [21]:
pd.concat([dframe1,dframe2],ignore_index=True) #provide continuous index

q         x         y         z
0       NaN  0.964260 -0.787730  0.120274
1       NaN  0.557330 -1.408828  0.217862
2       NaN -0.010404  0.829389  0.419324
3       NaN  0.358809 -0.026852  0.906940
4  0.477203  0.274342  2.160294       NaN
5  1.028196 -1.242782 -1.665423       NaN
6 -0.932193  0.783536 -0.572431       NaN

In [20]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.html'