In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.00978892, -0.58587351,  1.45940304,  0.34560325, -0.99224507,
       -0.18270562,  1.35526382, -1.34474958,  0.21936555, -1.08331816])

In [6]:
B = np.random.randn(10)
B

array([ 0.64379534,  0.50897799,  0.85646409, -0.95898214,  0.71637658,
       -1.02992416,  0.57235998, -0.49729464, -0.44340355,  0.27371385])

In [7]:
# Binary Functions - functions that use 2 arrays
np.add(A,B)

array([ 0.65358426, -0.07689551,  2.31586712, -0.61337888, -0.27586849,
       -1.21262978,  1.9276238 , -1.84204422, -0.22403801, -0.80960431])

In [8]:
np.maximum(A,B)

array([ 0.64379534,  0.50897799,  1.45940304,  0.34560325,  0.71637658,
       -0.18270562,  1.35526382, -0.49729464,  0.21936555,  0.27371385])

In [9]:
np.minimum(A,B)

array([ 0.00978892, -0.58587351,  0.85646409, -0.95898214, -0.99224507,
       -1.02992416,  0.57235998, -1.34474958, -0.44340355, -1.08331816])

In [10]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True